application: gdgprosandcons
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
-   url: /favicon.ico
    static_files: media/img/favicon.ico
    upload: media/img/favicon.ico

-   url: /static
    static_dir: static

-   url: /_ah/spi/.*
    script: main.api_application

-   url: /meetup_api/refresh_db
    script: main.application
    login: admin

-   url: /.*
    script: main.application


libraries:
-   name: pycrypto
    version: latest

-   name: endpoints
    version: 1.0

-   name: webapp2   
    version: latest

-   name: jinja2
    version: latest